# Generated by Django 5.2.7 on 2025-10-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallate', '0004_message_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='art_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
