# Generated by Django 5.2.7 on 2025-10-29 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pallate', '0006_artwork_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
    ]
