# Generated by Django 4.2.25 on 2025-10-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pallate', '0008_alter_favorite_options_favorite_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
    ]
