# Generated by Django 5.2.7 on 2025-11-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallate', '0011_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reaction',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
