# Generated by Django 5.2.7 on 2025-12-02 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallate', '0011_message_image_message_reaction_alter_message_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, default='', help_text='Comma-separated interests (e.g., Fantasy Art, Portraits, Digital Painting)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured artist status'),
        ),
        migrations.CreateModel(
            name='CollaborationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='pallate.collaboration')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('collaboration', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='CollaborationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(default=0, help_text='Higher score = better match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_contacted', models.BooleanField(default=False)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_matches', to='pallate.collaboration')),
                ('suggested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('collaboration', 'suggested_user')},
            },
        ),
    ]
