# Generated by Django 5.2.7 on 2025-12-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallate', '0012_profile_interests_profile_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='security_answer',
            field=models.CharField(blank=True, default='', help_text='Answer to security question (stored hashed)', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_question',
            field=models.CharField(blank=True, default='', help_text='Security question for password recovery', max_length=255),
        ),
    ]
