# Generated by Django 5.2.7 on 2025-12-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallate', '0015_alter_collaboration_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='requirements',
            field=models.TextField(blank=True, help_text='Project requirements (one per line)'),
        ),
    ]
