# Generated by Django 5.2.7 on 2025-12-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallate', '0016_collaboration_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability_status',
            field=models.CharField(blank=True, default='Available for projects', help_text='Current availability', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='hourly_rate',
            field=models.CharField(blank=True, default='', help_text='e.g., $50-150/hour', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', help_text='City, State/Country', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_active',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True),
        ),
    ]
