# Generated by Django 5.2.7 on 2025-12-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallate', '0017_profile_availability_status_profile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='categories',
            field=models.CharField(blank=True, help_text='Comma-separated categories', max_length=255),
        ),
    ]
