# Generated by Django 5.2.7 on 2025-12-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pallate', '0018_artwork_categories'),
    ]

    operations = [
        # Attempt to remove the category field if it exists
        # This is a no-op if the field doesn't exist
        migrations.RunSQL(
            "ALTER TABLE pallate_artwork DROP COLUMN IF EXISTS category;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]