# Generated by Django 5.2.7 on 2025-12-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallate', '0019_remove_artwork_category'),
    ]

    operations = [
        # Make categories field nullable to avoid constraint issues
        migrations.RunSQL(
            "ALTER TABLE pallate_artwork ALTER COLUMN categories DROP NOT NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]