# Generated by Django 5.2.7 on 2025-12-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallate', '0020_fix_artwork_category_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='categories',
            field=models.CharField(blank=True, help_text='Comma-separated categories', max_length=255, null=True),
        ),
    ]
