# Generated by Django 5.2.7 on 2025-12-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pallate', '0018_artwork_category'),
        ('pallate', '0021_alter_artwork_categories'),
    ]

    operations = [
    ]
